import { getAppSetting, setAppSetting, deleteAppSetting } from './store'
import { renderBrandIconPngDataUrl } from './brandIconRaster'

/**
 * Appearance / branding settings - app name, primary color, and logo
 * overrides. Same pattern as authSettings.ts: defaults come from runtime
 * config / built-in assets, admins can override from the UI, and the
 * override is stored as one JSON blob in app_settings. Unlike auth settings,
 * this is read by unauthenticated visitors too (the login screen needs the
 * branding before anyone signs in), so there is no secret data here.
 */

export interface AppearanceSettings {
  appName: string
  /** Hex color, e.g. #2496ED. Drives --ui-primary and the app's accent color. */
  primaryColor: string
  /** Empty string means "use the built-in KNetraHub wordmark". */
  logoHorizontalUrl: string
  /** Empty string means "use the built-in KNetraHub icon". */
  logoIconUrl: string
  /** Empty string means "use the built-in KNetraHub favicon". Browser tab icon. */
  faviconUrl: string
  /** Empty string means "use the built-in KNetraHub app icon". Drives the PWA manifest icons and the Apple touch icon. */
  pwaIconUrl: string
  /** True when faviconUrl was generated server-side from primaryColor rather
   *  than uploaded - lets a later color change keep it in sync; a real
   *  upload clears this and is left untouched by future color changes until
   *  the admin explicitly clears/replaces it. See saveAppearanceSettings. */
  faviconAutoGenerated: boolean
  /** Same as faviconAutoGenerated, for pwaIconUrl. */
  pwaIconAutoGenerated: boolean
}

const KEY = 'appearance'

export const DEFAULT_PRIMARY_COLOR = '#2496ED'

/** Config/built-in defaults only - no DB read. Exported so the static docs
 *  build can serve appearance without ever touching Postgres. */
export function defaultAppearanceSettings(): AppearanceSettings {
  return {
    appName: useRuntimeConfig().public.appName || 'KNetraHub',
    primaryColor: DEFAULT_PRIMARY_COLOR,
    logoHorizontalUrl: '',
    logoIconUrl: '',
    faviconUrl: '',
    pwaIconUrl: '',
    faviconAutoGenerated: true,
    pwaIconAutoGenerated: true
  }
}

async function readOverrides(): Promise<Partial<AppearanceSettings> | null> {
  const raw = await getAppSetting(KEY)
  if (!raw) return null
  try {
    return JSON.parse(raw) as Partial<AppearanceSettings>
  } catch {
    return null
  }
}

export async function getAppearanceSettings(): Promise<AppearanceSettings> {
  const overrides = await readOverrides()
  const merged = { ...defaultAppearanceSettings(), ...overrides }
  // Back-compat: settings saved before auto-icon-generation existed have no
  // faviconAutoGenerated/pwaIconAutoGenerated key in the stored JSON - treat
  // an already-uploaded icon as a real upload (never silently overwrite it),
  // only defaulting to auto mode when nothing was ever uploaded.
  if (overrides && overrides.faviconAutoGenerated === undefined) merged.faviconAutoGenerated = !merged.faviconUrl
  if (overrides && overrides.pwaIconAutoGenerated === undefined) merged.pwaIconAutoGenerated = !merged.pwaIconUrl
  return merged
}

export async function hasAppearanceOverride(): Promise<boolean> {
  return (await getAppSetting(KEY)) !== null
}

export async function saveAppearanceSettings(patch: Partial<AppearanceSettings>, actor: string): Promise<AppearanceSettings> {
  const current = await getAppearanceSettings()
  const next: AppearanceSettings = { ...current, ...patch }

  // A favicon/pwaIcon value that actually changed in this save is the admin
  // taking manual control (a real upload) - drop out of auto mode so a later
  // color change never overwrites it.
  if (patch.faviconUrl !== undefined && patch.faviconUrl !== current.faviconUrl) next.faviconAutoGenerated = false
  if (patch.pwaIconUrl !== undefined && patch.pwaIconUrl !== current.pwaIconUrl) next.pwaIconAutoGenerated = false

  // Explicitly clearing a manual upload back to "" ("Use default") means
  // "stop overriding, let the app manage this again" - re-enter auto mode
  // rather than staying blank forever if the color is customized.
  if (patch.faviconUrl === '' && current.faviconUrl) next.faviconAutoGenerated = true
  if (patch.pwaIconUrl === '' && current.pwaIconUrl) next.pwaIconAutoGenerated = true

  // Keep any field still in auto mode in sync with the (possibly just-
  // changed) primary color - rendered as a real PNG and stored exactly like
  // an upload, so every platform (including Chrome's PWA install prompt)
  // picks it up; a plain SVG data URI isn't accepted there.
  const isDefaultColor = next.primaryColor === DEFAULT_PRIMARY_COLOR
  if (next.faviconAutoGenerated) next.faviconUrl = isDefaultColor ? '' : renderBrandIconPngDataUrl(next.primaryColor, 64)
  if (next.pwaIconAutoGenerated) next.pwaIconUrl = isDefaultColor ? '' : renderBrandIconPngDataUrl(next.primaryColor, 512)

  await setAppSetting(KEY, JSON.stringify(next), actor)
  return next
}

export async function resetAppearanceSettings(): Promise<void> {
  await deleteAppSetting(KEY)
}
