import type { Migration } from './types'

/**
 * Stage 8 — risk-engine + compliance execution.
 *
 * 1. `dedupe_key` on risk_events so the periodic evaluation engine is idempotent
 *    (an off-hours session or an overdue account must raise ONE event per
 *    bucket, not a fresh one every 30s sweep). Partial-unique so the existing
 *    inline `recordRisk()` calls (NULL key) are unaffected.
 * 2. `pam.report_runs` — the stored evidence snapshot for generated/scheduled
 *    reports: the actual generated bytes (bounded), checksum, and delivery
 *    outcome, so a compliance report can be produced, delivered, and later
 *    re-downloaded byte-for-byte with a verifiable integrity hash.
 * 3. `certification_campaigns.summary` — completion evidence snapshot.
 */
export const migration: Migration = {
  id: '0016_risk_engine',
  statements: [
    `ALTER TABLE pam.risk_events ADD COLUMN IF NOT EXISTS dedupe_key TEXT`,
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_pam_risk_events_dedupe
       ON pam.risk_events(dedupe_key) WHERE dedupe_key IS NOT NULL`,

    `ALTER TABLE pam.certification_campaigns ADD COLUMN IF NOT EXISTS summary TEXT`,

    `CREATE TABLE IF NOT EXISTS pam.report_runs (
      id TEXT PRIMARY KEY,
      report_key TEXT NOT NULL,
      name TEXT NOT NULL,
      format TEXT NOT NULL DEFAULT 'csv' CHECK (format IN ('csv','xlsx','pdf','json')),
      params TEXT,
      schedule_id TEXT,
      row_count INTEGER NOT NULL DEFAULT 0,
      size_bytes INTEGER NOT NULL DEFAULT 0,
      checksum TEXT,
      content BYTEA,
      generated_at TEXT NOT NULL,
      generated_by TEXT,
      delivered BOOLEAN NOT NULL DEFAULT false,
      delivery_channel TEXT,
      delivery_status TEXT,
      delivery_detail TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS idx_pam_report_runs_key ON pam.report_runs(report_key, generated_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_pam_report_runs_schedule ON pam.report_runs(schedule_id, generated_at DESC)`
  ]
}
